// Generates `src/index.ts` so `@chiselart/ui` exports EVERY component from its
// root entry (the whole point of the SDK): primitives (`components/ui/*`),
// Chisel-authored composed components (`components/*`), hooks, and `cn`.
// Run after adding components: `node scripts/gen-barrel.mjs`.
import { readdirSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const srcDir = resolve(dirname(fileURLToPath(import.meta.url)), '../src');

function modules(dir) {
  try {
    return readdirSync(resolve(srcDir, dir))
      .filter((f) => /\.tsx?$/.test(f))
      .filter((f) => !/\.(stories|spec|test)\.tsx?$/.test(f))
      .filter((f) => f !== 'index.ts')
      .map((f) => f.replace(/\.tsx?$/, ''))
      .sort();
  } catch {
    return [];
  }
}

const ui = modules('components/ui');
const composed = modules('components');
const hooks = modules('hooks');

const lines = [
  '// AUTO-GENERATED by scripts/gen-barrel.mjs — do not edit by hand.',
  '// The Chisel UI SDK exports every component from its root entry; run',
  '// `node scripts/gen-barrel.mjs` after adding a component to refresh.',
  '',
  '// Primitives (shadcn / Base UI)',
  ...ui.map((n) => `export * from './components/ui/${n}';`),
  '',
  '// Composed components (Chisel-authored)',
  ...composed.map((n) => `export * from './components/${n}';`),
];
if (hooks.length) {
  lines.push('', '// Hooks', ...hooks.map((n) => `export * from './hooks/${n}';`));
}
lines.push('', '// Utilities', "export { cn } from './lib/utils';", '');

writeFileSync(resolve(srcDir, 'index.ts'), lines.join('\n'));
console.log(
  `barrel: ${ui.length} primitives + ${composed.length} composed + ${hooks.length} hooks`,
);
