import type { EditorFeature, IEditor } from '../document/core/index.js';
import { mention } from '../document/features/mention/index.js';
import { inlineToken } from './triggers/inline-token.js';
import {
  invocationToken,
  referenceToken,
  type TriggerOption,
  type TriggerToken,
} from './triggers/trigger-token.js';
import type {
  ChatChannel,
  ChatChannelRef,
  ChatCommand,
  ChatCommandRef,
  ChatMention,
  ChatPerson,
} from './composer-types.js';

/**
 * The composer's shipped triggers, each bundling the interaction descriptor
 * (`token`, read by the menu + payload) with the render feature (`feature`, the
 * node + codec composed into the editor and the message view). `mentionTrigger`
 * (`@`, reference) reuses the document `mention()` node; `commandTrigger` (`/`,
 * invocation) generates its node through the inline-token factory. A host builds
 * its own trigger the same way and registers it alongside these.
 */
export interface ComposerTrigger<Kind extends string = string, Ref = unknown> {
  token: TriggerToken<Kind, Ref>;
  feature: EditorFeature;
}

/** People offered in the `@` menu - a static list (filtered by label) or an
 *  async source the caller filters. */
export interface MentionSource {
  people?: ChatPerson[];
  /** Async (or sync) source queried as the user types; supersedes `people` and
   *  the caller owns the filtering. */
  onQuery?(query: string): ChatPerson[] | Promise<ChatPerson[]>;
}

const personOption = (person: ChatPerson): TriggerOption => ({
  id: person.id,
  label: person.label,
  description: person.description,
  icon: person.icon,
});

const channelOption = (channel: ChatChannel): TriggerOption => ({
  id: channel.id,
  label: channel.label,
  description: channel.description,
  icon: channel.icon,
});

const commandOption = (command: ChatCommand): TriggerOption => ({
  id: command.id,
  label: command.label,
  slug: command.name || command.id,
  description: command.description,
  icon: command.icon,
});

/** The `@mention` trigger - a reference pill reusing the document mention node.
 *  Its menu row keeps the avatar-box media the standalone mention menu used. */
export function mentionTrigger(
  source: MentionSource = {},
): ComposerTrigger<'mention', ChatMention> {
  const { people = [], onQuery } = source;
  const token = referenceToken<'mention', ChatMention>('mention', '@', {
    nodeName: 'mention',
    source: onQuery
      ? (query) => Promise.resolve(onQuery(query)).then((list) => list.map(personOption))
      : () => people.map(personOption),
    // An async source owns its own filtering; a static list uses the default.
    filter: onQuery ? (options) => options : undefined,
    insert: (editor: IEditor, option) =>
      editor.run('insertMention', { id: option.id, label: option.label }),
    readRef: (attrs) => ({
      id: String(attrs.id ?? ''),
      label: String(attrs.label ?? ''),
    }),
    menuMediaClassName: 'size-8 rounded-md border bg-secondary text-base',
    emptyText: 'No people found',
  });
  return { token, feature: mention() };
}

/**
 * The `#channel` trigger - a second `reference`, generated entirely by the
 * inline-token factory (label display). It is the registry's generalisation
 * proof: a new trigger is this one descriptor, reusing the same generic menu,
 * node/codec factory, and payload mapping - no new component, no hand-written
 * node, no edit to `docToPayload`. Opt-in: register it in `ChatInput`'s
 * `triggers` (and pass the same list to `ChatMessageView` so its codec renders).
 */
export function channelTrigger(
  channels: ChatChannel[] = [],
): ComposerTrigger<'channel', ChatChannelRef> {
  const node = inlineToken({ kind: 'channel', char: '#', display: 'label' });
  const token = referenceToken<'channel', ChatChannelRef>('channel', '#', {
    nodeName: node.nodeName,
    source: () => channels.map(channelOption),
    insert: node.insert,
    readRef: (attrs) => {
      const ref = node.readRef(attrs);
      return { id: ref.id, label: ref.label };
    },
    emptyText: 'No channels found',
  });
  return { token, feature: node.feature };
}

/** The `/command` trigger - an invocation pill generated by the inline-token
 *  factory (slug display), preserving the start-only, one-leading, commit-on-
 *  space, backspace-restore behaviour. */
export function commandTrigger(
  commands: ChatCommand[] = [],
): ComposerTrigger<'command', ChatCommandRef> {
  const node = inlineToken({ kind: 'command', char: '/', display: 'slug' });
  const token = invocationToken<'command', ChatCommandRef>('command', '/', {
    nodeName: node.nodeName,
    source: () => commands.map(commandOption),
    insert: node.insert,
    readRef: (attrs) => {
      const ref = node.readRef(attrs);
      return { id: ref.id, label: ref.label, name: ref.slug || ref.id };
    },
    emptyText: 'No commands found',
  });
  return { token, feature: node.feature };
}

/** The features + tokens the read-only message view needs to render the shipped
 *  pills when a caller passes no explicit triggers. */
export const defaultComposerTriggers: () => ComposerTrigger[] = () => [
  mentionTrigger(),
  commandTrigger(),
];
